group: edge
language: php
php:
  - '7.1'
  - '7.2'

services:
  - sqlite3

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

before_script:
  - sudo service apache restart
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
