language: php
php:
  - '7.1'
  - '7.2'

services:
  - sqlite

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
